version: '3.8'

services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html
      - /Users/pierre.brickley/Muture/matthieu-cauchy/storage:/var/www/html/storage

    depends_on:
      - mysqldb

  mysqldb:
    platform: "linux/amd64"
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD:  ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: